apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: lab-hello-world-sample
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-hello-world-sample
    capacity: 10@
    expires: 60m
    orphaned: 5m
